pull_request_rules:
        
  - name: automatic merge master 
    conditions:
      - label=merge-when-green
      - label!=blocked
    actions:
      merge:
        method: merge
        strict: smart

  - name: automatic squash master
    conditions:
      - label=squash-when-green
      - label!=blocked
    actions:
      merge:
        method: squash
        strict: smart

  - name: backport patches to 1.0.x branch
    conditions:
      - base=master
      - merged
      - label=backport
      - label=1.0.x
    actions:
      backport:
        branches:
          - 1.0.x
      label:
        remove: [backport, 1.0.x]


